# Generated by Django 5.2.13 on 2026-04-18 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reminders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["user", "status", "due_at"],
                name="reminders_r_user_id_777413_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["person", "due_at"], name="reminders_r_person__69b264_idx"
            ),
        ),
    ]
