# Generated by Django 5.2.13 on 2026-04-18 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interactions", "0004_interactionjournalentry_follow_up_completed_at"),
        ("people", "0003_person_disconnection_streak_person_plant_growth"),
        ("reminders", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="kind",
            field=models.CharField(
                choices=[("custom", "Custom"), ("birthday", "Birthday")],
                default="custom",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="repeat",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["person", "kind"], name="reminders_r_person__52fd7d_idx"
            ),
        ),
    ]
