# Generated by Django 5.2.13 on 2026-04-18 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelationshipScoreEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("interaction_logged", "Interaction logged"),
                            ("cadence_goal_met", "Cadence goal met"),
                            ("reminder_completed", "Reminder completed"),
                            ("streak_bonus", "Streak bonus"),
                            ("profile_enriched", "Profile enriched"),
                            ("missed_goal", "Missed goal"),
                            ("repeated_miss", "Repeated miss"),
                            ("prolonged_inactivity", "Prolonged inactivity"),
                            ("recovery_bonus", "Recovery bonus"),
                        ],
                        max_length=32,
                    ),
                ),
                ("points_delta", models.SmallIntegerField()),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_events",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
