# Generated by Django 5.2.13 on 2026-04-18 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scoring", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="relationshipscoreevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="score_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="relationshipscoreevent",
            index=models.Index(
                fields=["user", "created_at"], name="scoring_rel_user_id_269086_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relationshipscoreevent",
            index=models.Index(
                fields=["person", "created_at"], name="scoring_rel_person__a759b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relationshipscoreevent",
            index=models.Index(
                fields=["event_type"], name="scoring_rel_event_t_08d2ce_idx"
            ),
        ),
    ]
