# Generated by Django 5.2.13 on 2026-04-18 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InteractionJournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("in_person", "In person"),
                            ("call", "Call"),
                            ("text", "Text"),
                            ("video_call", "Video call"),
                            ("event", "Event"),
                            ("gift", "Gift"),
                            ("other", "Other"),
                        ],
                        default="text",
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("body", models.TextField(blank=True)),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                            ("stressed", "Stressed"),
                            ("happy", "Happy"),
                            ("sad", "Sad"),
                            ("anxious", "Anxious"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "interaction_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("was_meaningful", models.BooleanField(default=True)),
                ("follow_up_needed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-interaction_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="InteractionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="InteractionTagMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
