# Generated by Django 5.2.13 on 2026-04-18 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("interactions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="interactionjournalentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interactiontagmap",
            name="interaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="interactions.interactionjournalentry",
            ),
        ),
        migrations.AddField(
            model_name="interactiontagmap",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="interactions.interactiontag",
            ),
        ),
        migrations.AddField(
            model_name="interactionjournalentry",
            name="tags",
            field=models.ManyToManyField(
                related_name="interactions",
                through="interactions.InteractionTagMap",
                to="interactions.interactiontag",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interactiontagmap",
            unique_together={("interaction", "tag")},
        ),
        migrations.AddIndex(
            model_name="interactionjournalentry",
            index=models.Index(
                fields=["user", "interaction_date"],
                name="interaction_user_id_48459f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interactionjournalentry",
            index=models.Index(
                fields=["person", "interaction_date"],
                name="interaction_person__f69236_idx",
            ),
        ),
    ]
