# Generated by Django 5.2.13 on 2026-04-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interactions", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactionjournalentry",
            name="follow_up_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
