# Generated by Django 5.2.13 on 2026-04-18 20:36

import django.db.models.deletion
from django.db import migrations, models


def seed_primary_participants(apps, schema_editor):
    InteractionJournalEntry = apps.get_model("interactions", "InteractionJournalEntry")
    InteractionParticipant = apps.get_model("interactions", "InteractionParticipant")
    for interaction in InteractionJournalEntry.objects.exclude(person_id__isnull=True):
        InteractionParticipant.objects.get_or_create(interaction_id=interaction.id, person_id=interaction.person_id)


class Migration(migrations.Migration):
    dependencies = [
        ("interactions", "0004_interactionjournalentry_follow_up_completed_at"),
        ("people", "0003_person_disconnection_streak_person_plant_growth"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interactions.interactionjournalentry",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="people.person"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interactionjournalentry",
            name="participants",
            field=models.ManyToManyField(
                related_name="journal_entries",
                through="interactions.InteractionParticipant",
                to="people.person",
            ),
        ),
        migrations.AddIndex(
            model_name="interactionparticipant",
            index=models.Index(
                fields=["person", "interaction"], name="interaction_person__84c12a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interactionparticipant",
            unique_together={("interaction", "person")},
        ),
        migrations.RunPython(seed_primary_participants, migrations.RunPython.noop),
    ]
