# Generated by Django 5.2.13 on 2026-04-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("nickname", models.CharField(blank=True, max_length=160)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("friend", "Friend"),
                            ("family", "Family"),
                            ("work", "Work"),
                            ("partner", "Partner"),
                            ("other", "Other"),
                        ],
                        default="friend",
                        max_length=20,
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("avatar_url", models.URLField(blank=True)),
                ("notes_summary", models.TextField(blank=True)),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "contact_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "plant_type",
                    models.CharField(
                        choices=[
                            ("sunflower", "Sunflower"),
                            ("tulip", "Tulip"),
                            ("orchid", "Orchid"),
                            ("cactus", "Cactus"),
                        ],
                        default="tulip",
                        max_length=20,
                    ),
                ),
                ("relationship_points", models.PositiveSmallIntegerField(default=50)),
                (
                    "relationship_health",
                    models.CharField(
                        choices=[
                            ("thriving", "Thriving"),
                            ("healthy", "Healthy"),
                            ("needs_attention", "Needs attention"),
                            ("at_risk", "At risk"),
                            ("dormant", "Dormant"),
                        ],
                        default="needs_attention",
                        max_length=24,
                    ),
                ),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("last_interaction_at", models.DateTimeField(blank=True, null=True)),
                ("next_goal_due_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-is_favorite", "name"),
            },
        ),
        migrations.CreateModel(
            name="PersonProfileDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hobby", "Hobby"),
                            ("like", "Like"),
                            ("dislike", "Dislike"),
                            ("food", "Food"),
                            ("trait", "Trait"),
                            ("gift_idea", "Gift idea"),
                            ("important_date", "Important date"),
                            ("topic", "Topic"),
                            ("habit", "Habit"),
                            ("preference", "Preference"),
                            ("allergy", "Allergy"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("category", "value"),
            },
        ),
    ]
