# Generated by Django 5.2.13 on 2026-04-18 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="personprofiledetail",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_details",
                to="people.person",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["user", "name"], name="people_pers_user_id_3519af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["relationship_health"], name="people_pers_relatio_e338ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["next_goal_due_at"], name="people_pers_next_go_25f7ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personprofiledetail",
            index=models.Index(
                fields=["category"], name="people_pers_categor_2865ba_idx"
            ),
        ),
    ]
