# Generated by Django 5.2.13 on 2026-04-18 16:31

from django.db import migrations, models


def seed_growth_from_current_streak(apps, schema_editor):
    Person = apps.get_model("people", "Person")
    for person in Person.objects.all():
        person.plant_growth = min(100, person.current_streak or 0)
        person.save(update_fields=["plant_growth"])


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="disconnection_streak",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="person",
            name="plant_growth",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(seed_growth_from_current_streak, migrations.RunPython.noop),
    ]
